#!/bin/bash

NC='\033[0m'
GREEN='\e[1;32m'
RED='\e[1;31m'
debug=$1

get_result() {
    num_test=$1
    cmd=$2
    ret1=$3
    ret2=$4

    diff_output=$(diff sortie1.txt sortie2.txt)

    if [ -z "$diff_output" ]; then
        echo -e "TEST[$num_test]: $cmd $GREEN OK $NC"
    else
        echo -e "TEST[$num_test]: $cmd $RED KO $NC"
        if [ "$debug" == "-debug" ]; then
            echo "Sortie attendue :"
            cat sortie1.txt
            echo $ret1
            echo "Sortie obtenue :"
            cat sortie2.txt
            echo $ret2
        fi
    fi
}

create_test() {
    num_test=$1
    args=$2
    cmd="./palindrome $args"
    ./palindrome $args > sortie1.txt
    ret1=$?
    ../palindrome $args > sortie2.txt
    ret2=$?
    get_result $num_test "$cmd" $ret1 $ret2
}

args=("-n" "-p" "-b" "-imin" "-imax")
arg=${args[$RANDOM % ${#args[@]}]}
val=$((RANDOM % 50 - 10))
cmd=""

#Test aléatoire
create_test 0 "$arg $val"
#Test ciblé
#test for the -n
create_test 1 "-n -1"
create_test 2 "-n 0"
create_test 3 "-n 1"
create_test 4 "-n 363"
create_test 5 "-n 52 -imin 2"
create_test 5 "-n 52 -b 5 -imin 2"
create_test 6 "-p 52"